import { Row, Col } from "antd";
import Head from "next/head";
import React, { useState } from "react";
import s from "../../styles/WriteBlog.module.scss";
import { Input, Button,notification } from "antd";
import { useMutation } from "@apollo/client";
import { CREATE_BLOG } from "../../apollo/mutation/CreateBlog";
import { useRouter } from "next/router";

const { TextArea } = Input;

const writeBlog = () => {
  const [createPost, { data, loading, error }] = useMutation(CREATE_BLOG);

  const router = useRouter();

  const [title, settitle] = useState("");
  const [body, setbody] = useState("");
  const [tag, settag] = useState("");

  const onChangeTitle = (e) => {
    settitle(e.target.value);
  };

  const onChangeBody = (e) => {
    setbody(e.target.value);
  };

  const onChangeTag = (e) => {
    settag(e.target.value);
  };

  const onClickPublish = () => {
    console.log("Title", title);
    console.log("Body", body);
    console.log("Tag", tag);

    createPost({
      variables: { title: title, body: body, tags: tag },
    })
      .then(
        (value) => (
            notification.success({
                duration: 3,
                message: `Yup, Your blog is publish now.`,
                description:`${title}`,
              }),
          router.push('/myBlog')
        )
      )
      .catch((error) => console.log("blog err", error));
  };

  return (
    <div className={s.mainWriteBlogContainer}>
      <Head>
        <title>Blogify | Bolg</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Assets/logoLight.png" />
      </Head>

      <div className={s.oneWrap}>
        <Row justify="center">
          <Col xs={16}>
            <div className={s.title}>
              <Input
                size="large"
                placeholder="Your blog title"
                onChange={onChangeTitle}
              />
            </div>
            <div className={s.body}>
              <TextArea
                placeholder="Write your things..."
                autoSize
                onChange={onChangeBody}
              />
            </div>
            <div className={s.tag}>
              <Input
                size="large"
                placeholder="Add tag"
                onChange={onChangeTag}
              />
            </div>
            <div className={s.btn}>
              <div className={s.menuItem}>
                <Button
                  loading={loading}
                  type="primary"
                  danger
                  shape="round"
                  onClick={onClickPublish}
                >
                  Publish
                </Button>
              </div>
            </div>
          </Col>
        </Row>
      </div>
    </div>
  );
};

export default writeBlog;
